server:
  service:
    name: "origadmin.server.v1"
    version: "v1.0.0"
    servers:
      - protocol: http
        http:
          addr: ${http_address:0.0.0.0:8000}
          network: tcp
          timeout: 180s
          tls_config:
            use_tls: false
            cert_file: ""
            key_file: ""
          enable_pprof: true

      - protocol: grpc
        grpc:
          addr: ${grpc_address:0.0.0.0:9000}
          network: tcp
          timeout: 180s
          tls_config:
            use_tls: false
            cert_file: ""
            key_file: ""
    
    clients: []
    middlewares: []

  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
    allowed_headers: ["*"]
    exposed_headers: ["Content-Length", "Content-Type"]
    allow_credentials: true
    max_age: 43200

  data: {}

discovery:
  name: ""
  type: CONSUL
  endpoints: ["${consul_address:127.0.0.1:8500}"]
  config:
    scheme: "http"
    token: ""
    health_check: false
    health_check_interval: 0
    timeout: 0
    deregister_critical_service_after: 0